kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: raw-block-volume-poc-pvc
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 1Gi
  storageClassName: topolvm-provisioner
